### ISSUE TITLE
Handle duplication when creating and bulk importing new users

### ISSUE THREAD

**Issue by tomnixon** [Maptio/maptio#469]
Steps to reproduce:

1. Create a new account in Maptio so the account will have one Admin user.
2. Import some users from a CSV including the user who is already in the system.
3. Maptio will create a duplicate user with the same email address but Standard privileges

Expected behaviour:
Any users in an imported CSV that are already in Maptio should be ignored by the import.

**Comment by rgoj** [comment]
This has a relatively high priority now because it will cause issues (now that the optional emails work has been deployed) that we will need to address manually - which takes ages - as happened already in the week after release.

**Comment by rgoj** [comment]
Closing this slightly outdated issue in favour of a new duplication epic: #671
