### ISSUE TITLE
Long roles get truncated in the tooltip

### ISSUE THREAD

**Issue by rgoj** [Maptio/maptio#840]
### Problem
For organisations that have long role titles (not even that long!), when you hover over someone's name in the map, the title can easily be cut off. We should be able to find a nice enough way of preventing this from happening. It should be a simple fix and might be a good first issue too.

Here is the support ticket where this was first reported: https://app.intercom.com/a/inbox/q3x5lnhp/inbox/shared/all/conversation/106323200014152

### Screenshot
<img width="786" alt="Screenshot 2023-10-19 at 10 44 11" src="https://github.com/Maptio/maptio/assets/4092165/ed9f9513-5e30-4ab5-9b5f-06e8e5503278">

### Instructions for reproducing
1. Open a map, add a person, add a role
2. Enter a relatively long title for the role
3. Hover over the person in the map

### Expected behavior
The full role title should display.

### Tasks
* [ ] Go back to the support ticket where this was raised and update it: https://app.intercom.com/a/inbox/q3x5lnhp/inbox/shared/all/conversation/106323200014152

**Comment by tomnixon** [comment]
Reported again by a customer today. @rgoj if this might be a relatively quick fix, could you fit it in during a convenient moment?

**Comment by rgoj** [comment]
Another mention here: https://app.intercom.com/a/inbox/q3x5lnhp/inbox/shared/all/conversation/106323200014892?view=List

(although worth adding that all three mentions come from one customer; still - it's important to them, so let's do this)

This might be a great warm up issue (perhaps along with #856 ) for getting back into the swing of things in January!
