### ISSUE TITLE
Decrease zoom level on selected circles

### ISSUE THREAD

**Issue by rgoj** [Maptio/maptio#856]
We discussed this some time ago and then Tom mentioned it again around the time of making final improvements to the outliner (see #846): 
> Not actually about the outliner, but just noting it here: This might have gotten lost during the summer, but remember in Pavilion Gardens we spoke about not zooming in quite so far when a circle is selected, so you can see a bit more context around it. Did we settle on 75% or 85% or something else?

Let's produce a few screenshots with some options to settle on the correct zoom level.

**Comment by rgoj** [comment]
I've just shipped to staging a version of this with zoom set to 75%. Here's a few other options:

**50%**
![zoom 50](https://github.com/Maptio/maptio/assets/4092165/ea299f52-c4e5-468e-900c-3bdc4aaa5f19)

**60%**
![zoom 60](https://github.com/Maptio/maptio/assets/4092165/ac1ef967-1827-4580-920b-c77a1558a151)

**70%**
![zoom 70](https://github.com/Maptio/maptio/assets/4092165/8a0d21f7-a1f2-4b35-a7f0-3eec54f6fb10)

**75%** (this is what's currently on staging)
![zoom 75](https://github.com/Maptio/maptio/assets/4092165/bfc93ec0-0937-4532-9d33-91b2c0bcd9ea)

**80%** 
![zoom 80](https://github.com/Maptio/maptio/assets/4092165/949b2b20-784a-49db-9b8d-45ca951fd845)

**90%** (this is what's on production)
![zoom 90 - current](https://github.com/Maptio/maptio/assets/4092165/fe134c8b-c376-4e6b-8e2f-1b7b5dd092df)

**100%** (just for comparison)
![zoom 100](https://github.com/Maptio/maptio/assets/4092165/fd00ae7b-56af-49f0-a254-311d16cd6ad5)


This is what this looks like on the expanded map:

**50%**
![zoom 50 - expanded](https://github.com/Maptio/maptio/assets/4092165/656cda15-c0f2-4cc5-b75f-75e0540f24c8)

**60%**
![zoom 60 - expanded](https://github.com/Maptio/maptio/assets/4092165/dbe2fd22-f576-44d7-9c24-721a15a61ec4)

**70%**
![zoom 70 - expanded](https://github.com/Maptio/maptio/assets/4092165/0b9e58ea-fbac-42c0-bf5b-65690aaab49d)

**75%** (this is what's currently on staging)
![zoom 75 - expanded](https://github.com/Maptio/maptio/assets/4092165/caba3343-93c4-4230-ba21-1ee8074e18d6)

**80%** 
![zoom 80 - expanded](https://github.com/Maptio/maptio/assets/4092165/70132669-a8e4-4390-8585-ee9fdadc7cbe)

**90%** (this is what's on production)
![zoom 90 - current - expanded](https://github.com/Maptio/maptio/assets/4092165/e4510b57-1dd1-4036-8b30-6ad0f072fb8a)

**100%** (just for comparison)
![zoom 100 - expanded](https://github.com/Maptio/maptio/assets/4092165/12415599-79f6-4752-b076-8113baaf9a23)

**Comment by tomnixon** [comment]
Thanks for the mock-ups @rgoj, that's really helpful. Yeah, I see the trade-off here - we have to either optimise for readability with a larger zoom level, or optimise for showing more context with a smaller zoom. It depends on the user's task at the time as to which is best, but whatever we optimise for, the user can then adjust the zoom manually, even though that's some extra work for them.

I think I agree with your comment on Slack that perhaps overall we should stick with optimising for readability as that seems like a more fundamental need for users, knowing they can always zoom out a bit to see more context. I think we should just reduce it a little bit to, say, 85% which will reduce the amount of the circle that's obscured by the toolbar on the right. Shall we go with that and ship this?

**Comment by rgoj** [comment]
Great, thanks for reviewing, @tomnixon ! Yeah, that sounds good, let's go with 85%, I'll ship that later today! :shipit:
